SET foreign_key_checks = 0;

DROP VIEW IF EXISTS `v1`;

DROP TABLE IF EXISTS `t1`;
DROP TABLE IF EXISTS `t2`;
DROP TABLE IF EXISTS `t3`;
DROP TABLE IF EXISTS `t4`;
DROP TABLE IF EXISTS `t5`;
DROP TABLE IF EXISTS `t6`;
DROP TABLE IF EXISTS `t7`;
DROP TABLE IF EXISTS `t8`;
DROP TABLE IF EXISTS `t9`;
