on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get Raku image
        uses: JJ/raku-test-action@main
      - run: cat /etc/alpine-release
            
