on: [ push, workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: rakudo-star:alpine
    services:
      mysql:
        image: percona:5.7
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_RANDOM_ROOT_PASSWORD: yes
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=4s --health-timeout=2s --health-retries=8
      postgresql:
        image: postgres:14
        env:
          POSTGRES_DB: test
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432
        options: --health-cmd="pg_isready" --health-interval=4s --health-timeout=2s --health-retries=8
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apk update
          apk add --no-cache mysql-client mariadb-connector-c-dev postgresql-client
          zef install --force --/test App::Prove6
          zef install --deps-only --test-depends --/test .
      - name: Run tests
        env:
          UPROOTED_MYSQL_HOST: 127.0.0.1
          UPROOTED_MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
          UPROOTED_MYSQL_USER: test
          UPROOTED_MYSQL_PASSWORD: test
          UPROOTED_MYSQL_DATABASE: test
          UPROOTED_POSTGRESQL_HOST: 127.0.0.1
          UPROOTED_POSTGRESQL_PORT: ${{ job.services.postgresql.ports[5432] }}
          UPROOTED_POSTGRESQL_USER: test
          UPROOTED_POSTGRESQL_PASSWORD: test
          UPROOTED_POSTGRESQL_DATABASE: test
        run: prove6
