on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependencies
        run: sudo apt-get update && sudo apt-get install libmysqlclient21 libmysqlclient-dev
      - name: Get Raku image
        uses: JJ/raku-test-action@main
            
