on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Dependencies
        run: |
            sudo apt-get update
            sudo apt-get install rakudo
            git clone https://github.com/ugexe/zef.git
            cd zef
            raku -I. bin/zef install .
            zef install --/test DBIish
      - name: Run Tests
        run: raku -v
            
