on: [ push, pull_request ]

jobs:
  test:
    runs-on: ubuntu-22.04
    services:
      mysql:
        image: percona:5.7
        env:
          MYSQL_DATABASE: test
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_RANDOM_ROOT_PASSWORD: yes
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=4s --health-timeout=2s --health-retries=8
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install rakudo
          git clone https://github.com/ugexe/zef.git
          cd zef
          sudo raku -I. bin/zef install .
          /usr/lib/perl6/site/bin/zef install --/test DBIish App::Prove6
      - name: Run tests
        env:
          UPROOTED_MYSQL_HOST: 127.0.0.1
          UPROOTED_MYSQL_PORT: ${{ job.services.mysql.ports[3306] }}
          UPROOTED_MYSQL_USER: test
          UPROOTED_MYSQL_PASSWORD: test
          UPROOTED_MYSQL_DATABASE: test
        run: |
          /home/runner/.raku/bin/prove6
            
